export declare const colors: {
    body: string;
    "dark-body": string;
    "dark-card": string;
    "dark-screen": string;
    input: string;
    primary: string;
    secondary: string;
    success: string;
    danger: string;
    warning: string;
    info: string;
    dark: string;
    light: string;
    muted: string;
    white: string;
    black: string;
    gray: string;
    "dark-hover": string;
    "gray-light": string;
    "gray-lighter": string;
    "gray-lightest": string;
    "gray-border": string;
    transparent: string;
};
