import React from "react";
import { ComponentMeta } from "@storybook/react";
declare const _default: ComponentMeta<React.ForwardRefExoticComponent<import("./AlertModal").AlertModalProps & React.RefAttributes<unknown>>>;
export default _default;
export declare const SuccessModal: () => JSX.Element;
export declare const InfoModal: () => JSX.Element;
export declare const WarningModal: () => JSX.Element;
export declare const DangerModal: () => JSX.Element;
export declare const QuestionModal: () => JSX.Element;
export declare const QuestionModalWitchAsyncResponse: () => JSX.Element;
